---
# tasks file for docker_install

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install Docker pre-requisites
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - curl

- name: Add Docker GPG key for Ubuntu system
  apt_key:
    url: "{{ docker_gpg_url }}"
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "{{ docker_repo_url }}"
    state: present

- name: Install Docker
  apt:
    name: "{{ docker_package_name }}"
    state: present

- name: Start and Enable Docker service
  service:
    name: docker
    state: started
    enabled: yes
- name: Verify Docker Installation
  command: docker --version
  register: docker_version_result
  changed_when: false
- name: Display Docker Version
  debug:
    msg: "Docker Version {{ docker_version_result.stdout }}"
